name: Bug report
description: Report a reproducible bug.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough details to reproduce it.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps and inputs.
      placeholder: |
        1. Run ...
        2. Provide packet ...
        3. Observe error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: "e.g. 3.11.8"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "e.g. Ubuntu 24.04 / Windows 11"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      render: shell
