name: Feature request
description: Propose an improvement or new capability.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: A clear description of the problem.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed approach.
      placeholder: What should be added/changed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any alternative solutions or workarounds.
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      placeholder: Why this matters for users/project direction.
